#!/bin/bash

export DEBUG=1
export serv=$1

if [ ! -z $serv ]
then
for i in `cat ./hosts/$serv`
do
	./checks/$i $serv
done

else

echo -e "\n" >/tmp/report
for i in `ls ./hosts/`
	do for x in `cat ./hosts/$i`
		do 
			./checks/$x $i > /dev/null
				if [ "$?" -ne 0 ]; then
					echo "Service $i has failed $x check!"
					echo "$i,$x,FAILED" >> /tmp/report
				else
					echo "Service $i has passed $x check."
					echo "$i,$x,GOOD" >> /tmp/report
				fi
	 done
done

fi
